packages:
  - packages/*
  - docs

catalog:
  '@commitlint/cli': ^20.5.0
  '@commitlint/config-conventional': ^20.5.0
  '@types/node': ^25.5.0
  lint-staged: ^16.4.0
  oxfmt: ^0.42.0
  oxlint: ^1.57.0
  simple-git-hooks: ^2.13.1
  tsdown: ^0.21.7
  turbo: ^2.8.21
  typescript: ^6.0.2

onlyBuiltDependencies:
  - simple-git-hooks
